//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WowMemoryReaderBM.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class spells
    {
        public int ID { get; set; }
        public Nullable<int> field1 { get; set; }
        public Nullable<int> Attributes { get; set; }
        public Nullable<int> AttributesEx { get; set; }
        public Nullable<int> AttributesExB { get; set; }
        public Nullable<int> AttributesExC { get; set; }
        public Nullable<int> AttributesExD { get; set; }
        public Nullable<int> AttributesExE { get; set; }
        public Nullable<int> AttributesExF { get; set; }
        public Nullable<int> AttributesExG { get; set; }
        public Nullable<int> AttributesExH { get; set; }
        public Nullable<int> field11 { get; set; }
        public Nullable<int> CastTimesID { get; set; }
        public Nullable<int> DurationID { get; set; }
        public Nullable<int> PowerID { get; set; }
        public Nullable<int> RangeID { get; set; }
        public Nullable<double> Speed { get; set; }
        public Nullable<int> VisualID1 { get; set; }
        public Nullable<int> VisualID2 { get; set; }
        public Nullable<int> IconID1 { get; set; }
        public Nullable<int> IconID2 { get; set; }
        public string Name { get; set; }
        public string NameSubtext { get; set; }
        public string Description { get; set; }
        public string AuraDescription { get; set; }
        public Nullable<int> SchoolMask { get; set; }
        public Nullable<int> RuneCostID { get; set; }
        public Nullable<int> MissileID { get; set; }
        public Nullable<int> DescriptionVariablesID { get; set; }
        public Nullable<int> DifficultyID { get; set; }
        public Nullable<double> field30 { get; set; }
        public Nullable<int> ScalingID { get; set; }
        public Nullable<int> AuraOptionsID { get; set; }
        public Nullable<int> AuraRestrictionsID { get; set; }
        public Nullable<int> CastingRequirementsID { get; set; }
        public Nullable<int> CategoriesID { get; set; }
        public Nullable<int> ClassOptionsID { get; set; }
        public Nullable<int> CooldownsID { get; set; }
        public Nullable<int> field38 { get; set; }
        public Nullable<int> EquippedItemsID { get; set; }
        public Nullable<int> InterruptsID { get; set; }
        public Nullable<int> LevelsID { get; set; }
        public Nullable<int> PowerID2 { get; set; }
        public Nullable<int> ReagentsID { get; set; }
        public Nullable<int> ShapeshiftID { get; set; }
        public Nullable<int> TargetRestrictionsID { get; set; }
        public Nullable<int> TotemsID { get; set; }
        public Nullable<int> field47 { get; set; }
    }
}
